# Generated by Django 5.2.8 on 2025-12-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudreposicion',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='ItemSolicitud',
        ),
        migrations.DeleteModel(
            name='SolicitudReposicion',
        ),
    ]
