# Generated by Django 5.2.8 on 2025-12-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_solicitudreposicion_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaingreso',
            old_name='fecha',
            new_name='fecha_emision',
        ),
        migrations.RenameField(
            model_name='facturaingreso',
            old_name='proveedor',
            new_name='proveedor_nombre',
        ),
        migrations.RemoveField(
            model_name='facturaingreso',
            name='numero',
        ),
        migrations.AddField(
            model_name='facturaingreso',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
        migrations.AddField(
            model_name='facturaingreso',
            name='folio',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaingreso',
            name='iva',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facturaingreso',
            name='neto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facturaingreso',
            name='proveedor_giro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facturaingreso',
            name='proveedor_rut',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaingreso',
            name='tipo_dte',
            field=models.PositiveSmallIntegerField(choices=[(33, 'Factura Electrónica (Afecta)'), (34, 'Factura Exenta Electrónica'), (52, 'Guía de Despacho'), (61, 'Nota de Crédito'), (56, 'Nota de Débito')], default=33),
        ),
        migrations.AddField(
            model_name='facturaingreso',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='precio_unitario',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
