# Generated by Django 5.2.8 on 2025-12-03 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_fecha_facturaingreso_fecha_emision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaingreso',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='facturaingreso',
            name='neto',
        ),
        migrations.RemoveField(
            model_name='facturaingreso',
            name='total',
        ),
        migrations.RemoveField(
            model_name='itemfactura',
            name='precio_unitario',
        ),
    ]
