# Generated by Django 5.2.8 on 2025-12-09 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_facturaingreso_iva_remove_facturaingreso_neto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaingreso',
            name='folio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='facturaingreso',
            constraint=models.UniqueConstraint(fields=('folio', 'proveedor_rut'), name='unique_folio_ingreso_por_proveedor'),
        ),
    ]
