# Generated by Django 5.2.8 on 2025-12-13 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_facturaingreso_folio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesechoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(choices=[('VENCIDO', 'Producto vencido'), ('DANADO', 'Producto dañado'), ('RETIRO_SANITARIO', 'Retiro sanitario'), ('OTRO', 'Otro')], max_length=30)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('item_factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desechos', to='inventario.itemfactura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
