# Generated by Django 5.2.8 on 2025-11-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('JEFE_BODEGA', 'Jefe de Bodega'), ('FUNC_BODEGA', 'Funcionario Bodega'), ('JEFE_FARMACIA', 'Jefe de Farmacia'), ('FUNC_FARMACIA', 'Funcionario Farmacia')], max_length=20),
        ),
    ]
