# Generated by Django 5.2.8 on 2025-12-04 03:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_facturafarmacia_itemfacturafarmacia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturafarmacia',
            old_name='fecha',
            new_name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='facturafarmacia',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='facturafarmacia',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='facturafarmacia',
            name='total_items',
        ),
        migrations.AddField(
            model_name='facturafarmacia',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturas_farmacia/'),
        ),
        migrations.AddField(
            model_name='facturafarmacia',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturafarmacia',
            name='folio',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturafarmacia',
            name='proveedor_giro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facturafarmacia',
            name='proveedor_nombre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturafarmacia',
            name='proveedor_rut',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturafarmacia',
            name='tipo_dte',
            field=models.PositiveSmallIntegerField(choices=[(33, 'Factura Electrónica (Afecta)'), (34, 'Factura Exenta Electrónica'), (52, 'Guía de Despacho'), (61, 'Nota de Crédito'), (56, 'Nota de Débito')], default=33),
        ),
    ]
