# Generated by Django 5.2.8 on 2025-12-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_rename_fecha_facturafarmacia_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofarmacia',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='farmacia.facturafarmacia'),
        ),
    ]
