# Generated by Django 5.2.8 on 2025-12-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_dispensacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensacion',
            name='dosis',
        ),
        migrations.AddField(
            model_name='dispensacion',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
