# Generated by Django 5.2.8 on 2025-12-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_remove_dispensacion_dosis_dispensacion_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=100)),
                ('vencimiento', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento')),
            ],
        ),
    ]
