# Generated by Django 5.2.8 on 2025-12-09 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0008_lotefarmacia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturafarmacia',
            name='folio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='facturafarmacia',
            constraint=models.UniqueConstraint(fields=('folio', 'proveedor_rut'), name='unique_folio_por_proveedor'),
        ),
    ]
